# Generated by Django 2.1.1 on 2018-10-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181008_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee paid by Event organizer to athlete.photo', max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_paid',
            field=models.BooleanField(default=False, help_text='Event fee has been paid in full'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal/private notes regarding the event. For use by athlete.photo only.', verbose_name='Internal Notes'),
        ),
    ]
