# Generated by Django 2.1.2 on 2018-10-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181009_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Ride', 'Ride'), ('Run', 'Run'), ('Swim', 'Swim'), ('Triathlon', 'Triathlon'), ('Other', 'Other')], default='Other', max_length=12),
        ),
    ]
