# Generated by Django 2.1.2 on 2018-10-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
