# Generated by Django 2.1.2 on 2018-10-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20181025_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='state_provenance',
        ),
        migrations.AddField(
            model_name='event',
            name='state_province',
            field=models.CharField(blank=True, help_text='State, region, or province for event meeting place', max_length=100, verbose_name='State or Province'),
        ),
    ]
