# Generated by Django 2.1.2 on 2018-10-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(help_text='One or more organizations that sponsor or support this event.', to='events.Organization'),
        ),
    ]
