# Generated by Django 2.1.2 on 2018-10-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='One or more organizations that sponsor or support this event.', to='events.Organization'),
        ),
    ]
