# Generated by Django 2.1.2 on 2018-10-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='official_event_site_url',
        ),
    ]
