# Generated by Django 2.1.2 on 2018-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_official_event_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place_name',
            field=models.CharField(blank=True, help_text='Name of the site, building, or area where event begins.', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('roadbike', 'Cycling'), ('hike', 'Hike'), ('mtb', 'Mountain Bike'), ('run', 'Run'), ('swim', 'Swim'), ('tri', 'Triathlon'), ('other', 'Other')], default='other', max_length=12),
        ),
    ]
