# Generated by Django 2.1.2 on 2018-10-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20181028_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='human',
        ),
    ]
