# Generated by Django 2.1.2 on 2018-10-29 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0018_remove_event_human'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='humans',
            field=models.ManyToManyField(blank=True, help_text='Another user on athlete.photo functioning as a contact for this event.', to=settings.AUTH_USER_MODEL, verbose_name='Human Contact'),
        ),
    ]
