# Generated by Django 2.1.2 on 2018-11-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_humans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='humans',
            new_name='organizers',
        ),
    ]
