# Generated by Django 2.1.2 on 2018-11-22 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20181122_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text='Other users on athlete.photo functioning as organizers for this event.', to=settings.AUTH_USER_MODEL),
        ),
    ]
