# Generated by Django 2.1.2 on 2018-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20181122_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Something', max_length=140, verbose_name='Event Title'),
            preserve_default=False,
        ),
    ]
