# Generated by Django 2.1.2 on 2018-11-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20181123_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, help_text='Street address/location for event meeting place. Do not include city/state/country.', max_length=255, null=True, verbose_name='Start Place Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='official_event_site_title',
            field=models.CharField(blank=True, help_text='Site title for primary Event page. Will be linked to External Event Website URL.', max_length=200, verbose_name='External Event Website Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='official_event_site_url',
            field=models.URLField(blank=True, help_text='URL for primary Event page (can be elsewhere on the internet)', null=True, verbose_name='External Event Website URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='One or more organizations that sponsor or support this event', to='events.Organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_name',
            field=models.CharField(blank=True, help_text='Name of the site, building, or area where event begins.', max_length=100, verbose_name='Start Place Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, help_text='Unpublished events are hidden from public display.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Date and time for start of event.', null=True, verbose_name='Start Date and Time'),
        ),
    ]
