# Generated by Django 2.1.2 on 2018-11-25 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_photographers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text='Other users on athlete.photo functioning as organizers for this event.', limit_choices_to={'groups__name': 'Organizers'}, related_name='event_organizers', to=settings.AUTH_USER_MODEL),
        ),
    ]
