# Generated by Django 2.1.1 on 2018-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('org_link', models.URLField(blank=True, help_text="Used to link back to the organization's homepage (or to any URL).")),
            ],
        ),
    ]
