# Generated by Django 2.1.1 on 2018-09-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
    ]
