# Generated by Django 2.1.2 on 2018-10-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181020_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='Something about you.'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='An image of you, to be used with your profile.', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, help_text='Your Facebook username (not URL).', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Your LinkedIn username (not URL).', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_website',
            field=models.URLField(blank=True, help_text='Your blog, profile, or hobby website or page URL.'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_website',
            field=models.URLField(blank=True, help_text='Your work-related website or profile page URL.'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, help_text='Your Twitter username (not URL).', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
