# Generated by Django 2.1.2 on 2018-10-21 07:43

import ap.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181020_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='Your bio / about you.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ap_organizations',
            field=models.ManyToManyField(blank=True, help_text='Groups or organizations registered on athlete.photo, of which this user is a member.', to='users.Organization', verbose_name='AP Orgs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='An image of you, to be used with your profile.', null=True, upload_to=ap.apps.users.models.get_avatar_upload_dir),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='We will never display your email on the website.', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Your LinkedIn username (not URL).', max_length=100, verbose_name='LinkedIn'),
        ),
    ]
