# Generated by Django 2.1.2 on 2018-10-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181021_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_edited',
            field=models.BooleanField(default=False, help_text='Alert user if they have never set up their profile'),
        ),
    ]
