# Generated by Django 2.1.2 on 2018-10-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, help_text='Your Instagram username (not URL).', max_length=100),
        ),
    ]
