# Generated by Django 2.1.2 on 2018-10-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ap_organizations',
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='A few sentences about you. Plain text only, no formatting.'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
