# Generated by Django 2.1.2 on 2018-10-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_organizations'),
        ('users', '0014_auto_20181025_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(help_text='One or more organizations with which this user is affiliated.', to='events.Organization'),
        ),
    ]
