# Generated by Django 2.1.2 on 2018-10-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='One or more organizations with which this user is affiliated.', to='events.Organization'),
        ),
    ]
