# Generated by Django 2.1.1 on 2018-10-09 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
    ]
