# Generated by Django 2.1.1 on 2018-10-10 06:04

import ap.apps.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=ap.apps.photos.models.event_photo_filename),
        ),
    ]
