# Generated by Django 2.1.2 on 2018-10-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20181009_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='subject',
        ),
    ]
