# Generated by Django 2.1.2 on 2018-10-20 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0005_remove_photo_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='subjects',
            field=models.ManyToManyField(help_text='Participants visible in this photo.', to=settings.AUTH_USER_MODEL),
        ),
    ]
