# Generated by Django 2.1.2 on 2018-10-20 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Participants visible in this photo.', to=settings.AUTH_USER_MODEL),
        ),
    ]
